CREATE DATABASE pw3_ingressos;

USE pw3_ingressos;

CREATE TABLE TBL_FILME (
    ID_FILME            BIGINT          IDENTITY(1, 1) NOT NULL,
    TX_NOME             VARCHAR(255)    NULL,
    NR_DURACAO          INT             NULL,
    TP_CATEGORIA        VARCHAR(50)     NULL,  /* CategoriaFilmeEnum */
    TP_CLASSIFICACAO    VARCHAR(50)     NULL,  /* ClassificacaoIndicativaEnum */
    NR_ANO              INT             NULL,
    TX_CAPA             VARCHAR(255)    NULL,
    TX_DIRETOR          VARCHAR(255)    NULL,
    TX_ELENCO           VARCHAR(255)    NULL,
    TX_DESCRICAO        VARCHAR(255)    NULL,
    NR_AVALIACAO        FLOAT           NULL,
    CHK_EM_CARTAZ       VARCHAR(10)     NULL,  /* SimNaoEnum: S, N */
    DT_EXCLUSAO         DATETIME2(6)    NULL,
    CONSTRAINT PK_TBL_FILME PRIMARY KEY (ID_FILME)
);

CREATE TABLE TBL_SALA (
    ID_SALA             BIGINT          IDENTITY(1, 1) NOT NULL,
    TX_NOME             VARCHAR(255)    NULL,
    NR_PRECO            FLOAT           NULL,
    DT_EXCLUSAO         DATETIME2(6)    NULL,
    CONSTRAINT PK_TBL_SALA PRIMARY KEY (ID_SALA)
);

CREATE TABLE TBL_LUGAR (
    ID_LUGAR            BIGINT          IDENTITY(1, 1) NOT NULL,
    TX_FILEIRA          VARCHAR(255)    NULL,
    NR_POSICAO          INT             NULL,
    ID_SALA             BIGINT          NOT NULL,
    CONSTRAINT PK_TBL_LUGAR PRIMARY KEY (ID_LUGAR),
    CONSTRAINT FK_TBL_LUGAR_TBL_SALA FOREIGN KEY (ID_SALA)
        REFERENCES TBL_SALA (ID_SALA)
);

CREATE TABLE TBL_SESSAO (
    ID_SESSAO           BIGINT          IDENTITY(1, 1) NOT NULL,
    DT_DATA             DATETIME2(6)    NULL,
    NR_PRECO            FLOAT           NULL,
    ID_SALA             BIGINT          NOT NULL,
    ID_FILME            BIGINT          NOT NULL,
    DT_EXCLUSAO         DATETIME2(6)    NULL,
    CONSTRAINT PK_TBL_SESSAO PRIMARY KEY (ID_SESSAO),
    CONSTRAINT FK_TBL_SESSAO_TBL_SALA FOREIGN KEY (ID_SALA)
        REFERENCES TBL_SALA (ID_SALA),
    CONSTRAINT FK_TBL_SESSAO_TBL_FILME FOREIGN KEY (ID_FILME)
        REFERENCES TBL_FILME (ID_FILME)
);

CREATE TABLE TBL_INGRESSO (
    ID_INGRESSO         BIGINT          IDENTITY(1, 1) NOT NULL,
    TP_INGRESSO         VARCHAR(50)     NULL,  /* TipoIngressoEnum */
    NR_PRECO            FLOAT           NULL,
    ID_SESSAO           BIGINT          NULL,
    ID_LUGAR            BIGINT          NULL,
    CONSTRAINT PK_TBL_INGRESSO PRIMARY KEY (ID_INGRESSO),
    CONSTRAINT FK_TBL_INGRESSO_TBL_SESSAO FOREIGN KEY (ID_SESSAO)
        REFERENCES TBL_SESSAO (ID_SESSAO),
    CONSTRAINT FK_TBL_INGRESSO_TBL_LUGAR FOREIGN KEY (ID_LUGAR)
        REFERENCES TBL_LUGAR (ID_LUGAR)
);

CREATE TABLE TBL_PEDIDO (
    ID_PEDIDO           BIGINT          IDENTITY(1, 1) NOT NULL,
    TX_NUMERO           VARCHAR(255)    NULL,
    DT_CRIACAO          DATETIME2(6)    NULL,
    TP_STATUS           VARCHAR(50)     NULL,  /* StatusPedidoEnum */
    CONSTRAINT PK_TBL_PEDIDO PRIMARY KEY (ID_PEDIDO)
);

CREATE TABLE TBL_PAGAMENTO (
    ID_PAGAMENTO        BIGINT          IDENTITY(1, 1) NOT NULL,
    NR_VALOR            FLOAT           NULL,
    TP_STATUS           VARCHAR(50)     NULL,  /* StatusPagamentoEnum */
    ID_PEDIDO           BIGINT          NOT NULL,
    CONSTRAINT PK_TBL_PAGAMENTO PRIMARY KEY (ID_PAGAMENTO),
    CONSTRAINT UQ_TBL_PAGAMENTO_ID_PEDIDO UNIQUE (ID_PEDIDO),
    CONSTRAINT FK_TBL_PAGAMENTO_TBL_PEDIDO FOREIGN KEY (ID_PEDIDO)
        REFERENCES TBL_PEDIDO (ID_PEDIDO)
);

CREATE TABLE TBL_DADOS_PAGAMENTO (
    ID_DADOS_PAGAMENTO  BIGINT          IDENTITY(1, 1) NOT NULL,
    TX_NOME             VARCHAR(255)    NULL,
    TX_EMAIL            VARCHAR(255)    NULL,
    TX_NUMERO           VARCHAR(255)    NULL,
    TX_EXPIRACAO        VARCHAR(255)    NULL,
    TX_BANDEIRA         VARCHAR(255)    NULL,
    TX_CODIGO           VARCHAR(255)    NULL,
    NR_PARCELAS         INT             NULL,
    NR_VALOR            FLOAT           NULL,
    TP_TIPO             VARCHAR(50)     NULL,  /* TipoFormaPagamentoEnum */
    ID_PAGAMENTO        BIGINT          NOT NULL,
    CONSTRAINT PK_TBL_DADOS_PAGAMENTO PRIMARY KEY (ID_DADOS_PAGAMENTO),
    CONSTRAINT UQ_TBL_DADOS_PAGAMENTO_ID_PAGAMENTO UNIQUE (ID_PAGAMENTO),
    CONSTRAINT FK_TBL_DADOS_PAGAMENTO_TBL_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO)
        REFERENCES TBL_PAGAMENTO (ID_PAGAMENTO)
);

CREATE TABLE TBL_REL_PEDIDO_INGRESSO (
    ID_PEDIDO           BIGINT          NOT NULL,
    ID_INGRESSO         BIGINT          NOT NULL,
    CONSTRAINT PK_TBL_REL_PEDIDO_INGRESSO PRIMARY KEY (ID_PEDIDO, ID_INGRESSO),
    CONSTRAINT FK_TBL_REL_PEDIDO_INGRESSO_PEDIDO FOREIGN KEY (ID_PEDIDO)
        REFERENCES TBL_PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_TBL_REL_PEDIDO_INGRESSO_INGRESSO FOREIGN KEY (ID_INGRESSO)
        REFERENCES TBL_INGRESSO (ID_INGRESSO)
);


INSERT INTO TBL_FILME(TX_NOME, NR_DURACAO, TP_CATEGORIA, TP_CLASSIFICACAO, CHK_EM_CARTAZ, NR_ANO, TX_CAPA, TX_DIRETOR, TX_ELENCO, TX_DESCRICAO, NR_AVALIACAO)
VALUES ('Inception', 148, 'FICCAO_CIENTIFICA', 'A14', 'N', 2010, 'https://m.media-amazon.com/images/I/91cVXf75GXL._AC_UF1000,1000_QL80_.jpg', 'Christopher Nolan', 'Leonardo DiCaprio; Joseph Gordon-Levitt', 'Um ladrão invade sonhos para roubar segredos corporativos.', 8.8);

INSERT INTO TBL_FILME (TX_NOME, NR_DURACAO, TP_CATEGORIA, TP_CLASSIFICACAO, CHK_EM_CARTAZ, NR_ANO, TX_CAPA, TX_DIRETOR, TX_ELENCO, TX_DESCRICAO, NR_AVALIACAO)
VALUES('The Dark Knight', 152, 'ACAO', 'A14', 'N', 2008, 'https://www.europanet.com.br/upload/id_produto/45_____/4500402g.jpg', 'Christopher Nolan', 'Christian Bale; Heath Ledger', 'Batman enfrenta o Coringa em Gotham City.', 9.0);

INSERT INTO TBL_FILME (TX_NOME, NR_DURACAO, TP_CATEGORIA, TP_CLASSIFICACAO, CHK_EM_CARTAZ, NR_ANO, TX_CAPA, TX_DIRETOR, TX_ELENCO, TX_DESCRICAO, NR_AVALIACAO)
VALUES ('Titanic', 195, 'ROMANCE', 'A12', 'S', 1997, 'https://m.media-amazon.com/images/I/61eVG8G5r9L._AC_UF894,1000_QL80_.jpg', 'James Cameron', 'Leonardo DiCaprio; Kate Winslet', 'Um romance surge a bordo do famoso navio Titanic.', 7.9);

INSERT INTO TBL_FILME (TX_NOME, NR_DURACAO, TP_CATEGORIA, TP_CLASSIFICACAO, CHK_EM_CARTAZ, NR_ANO, TX_CAPA, TX_DIRETOR, TX_ELENCO, TX_DESCRICAO, NR_AVALIACAO)
VALUES ('The Godfather', 175, 'DRAMA', 'A16', 'N', 1972, 'https://www.cineplayers.com/sites/default/files/posters/2020/08/god.jpg', 'Francis Ford Coppola', 'Marlon Brando; Al Pacino', 'A história da poderosa família mafiosa Corleone.', 9.2);

INSERT INTO TBL_FILME (TX_NOME, NR_DURACAO, TP_CATEGORIA, TP_CLASSIFICACAO, CHK_EM_CARTAZ, NR_ANO, TX_CAPA, TX_DIRETOR, TX_ELENCO, TX_DESCRICAO, NR_AVALIACAO)
VALUES ('Avengers: Endgame', 181, 'AVENTURA', 'A12', 'S', 2019, 'https://sm.ign.com/ign_pt/screenshot/default/d1nmwmgvaaajv5mjpg-large_4c7c.jpg', 'Anthony Russo; Joe Russo', 'Robert Downey Jr.; Chris Evans', 'Os Vingadores enfrentam Thanos na batalha final.', 8.4);

INSERT INTO TBL_FILME (TX_NOME, NR_DURACAO, TP_CATEGORIA, TP_CLASSIFICACAO, CHK_EM_CARTAZ, NR_ANO, TX_CAPA, TX_DIRETOR, TX_ELENCO, TX_DESCRICAO, NR_AVALIACAO)
VALUES ('Toy Story', 81, 'ANIMACAO', 'LIVRE', 'N', 1995, 'https://s2-gshow.glbimg.com/wjfmRjiuFFNFKktDsARFAxvaeN8=/0x0:688x1024/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_e84042ef78cb4708aeebdf1c68c6cbd6/internal_photos/bs/2021/s/7/U0i9uYRDeY1eiEBGXP2A/toy-story-imdb-divulgacao.jpeg', 'John Lasseter', 'Tom Hanks; Tim Allen', 'Brinquedos ganham vida quando humanos não estão por perto.', 8.3);

INSERT INTO TBL_SALA (TX_NOME, NR_PRECO, DT_EXCLUSAO)
VALUES
('Sala 1 - Premium', 45.00, NULL),
('Sala 2 - 3D', 40.00, NULL),
('Sala 3 - IMAX', 55.00, NULL),
('Sala 4 - Convencional', 30.00, NULL),
('Sala 5 - VIP', 60.00, NULL);

INSERT INTO TBL_SESSAO (DT_DATA, NR_PRECO, ID_SALA, ID_FILME, DT_EXCLUSAO)
VALUES
(CAST(CAST(GETDATE() AS DATE) AS DATETIME) + CAST('14:00:00' AS DATETIME), 45.00, 1, 1, NULL),
(CAST(CAST(GETDATE() AS DATE) AS DATETIME) + CAST('17:00:00' AS DATETIME), 45.00, 1, 2, NULL),
(CAST(CAST(GETDATE() AS DATE) AS DATETIME) + CAST('20:00:00' AS DATETIME), 45.00, 1, 3, NULL),

(DATEADD(DAY, 1, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) 
        + CAST('15:00:00' AS DATETIME), 40.00, 2, 4, NULL),
(DATEADD(DAY, 1, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) 
        + CAST('18:00:00' AS DATETIME), 40.00, 2, 5, NULL),
(DATEADD(DAY, 1, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) 
        + CAST('21:00:00' AS DATETIME), 40.00, 2, 6, NULL),

(DATEADD(DAY, 2, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) 
        + CAST('19:00:00' AS DATETIME), 30.00, 4, 1, NULL),
(DATEADD(DAY, 2, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) 
        + CAST('22:00:00' AS DATETIME), 30.00, 4, 2, NULL),

(DATEADD(DAY, 3, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) 
        + CAST('13:30:00' AS DATETIME), 60.00, 5, 3, NULL),
(DATEADD(DAY, 3, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) 
        + CAST('16:30:00' AS DATETIME), 60.00, 5, 4, NULL),
(DATEADD(DAY, 3, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) 
        + CAST('19:30:00' AS DATETIME), 60.00, 5, 5, NULL),
(DATEADD(DAY, 3, CAST(CAST(GETDATE() AS DATE) AS DATETIME)) 
        + CAST('22:30:00' AS DATETIME), 60.00, 5, 6, NULL);
